kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
nodes:
  - role: control-plane
    image: "kindest/node:v$KUBERNETES_VERSION"
    extraMounts:
      - hostPath: $PWD/k8s/.local-registry/
        containerPath: "/etc/containerd/certs.d/"
        readOnly: true
  - role: worker
    labels:
      topology.kubernetes.io/zone: "us-central1-a"
      ingress-ready: "true"
    image: "kindest/node:v$KUBERNETES_VERSION"
    extraMounts:
      - hostPath: $PWD/k8s/.local-registry/
        containerPath: "/etc/containerd/certs.d/"
        readOnly: true
    extraPortMappings:
    # Port for the ingress controller over http
    - containerPort: 30000
      hostPort: 80
      listenAddress: "127.0.0.1"
      protocol: TCP
    # Port for the ingress controller over https
    - containerPort: 30001
      hostPort: 443
      listenAddress: "127.0.0.1"
      protocol: TCP
  - role: worker
    labels:
      topology.kubernetes.io/zone: "us-central1-b"
      ingress-ready: "false"
    image: "kindest/node:v$KUBERNETES_VERSION"
    extraMounts:
      - hostPath: $PWD/k8s/.local-registry/
        containerPath: "/etc/containerd/certs.d/"
        readOnly: true
  - role: worker
    labels:
      topology.kubernetes.io/zone: "us-central1-c"
      ingress-ready: "false"
    image: "kindest/node:v$KUBERNETES_VERSION"
    extraMounts:
      - hostPath: $PWD/k8s/.local-registry/
        containerPath: "/etc/containerd/certs.d/"
        readOnly: true
