kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
kubeadmConfigPatches:
  - |-
    kind: ClusterConfiguration
    apiServer:
      extraVolumes:
        - name: opt-ca-certificates
          hostPath: /opt/ca-certificates/root-ca.pem
          mountPath: /opt/ca-certificates/root-ca.pem
          readOnly: true
          pathType: File
nodes:
  - role: control-plane
    image: "kindest/node:v$KUBERNETES_VERSION"
    extraMounts:
      - hostPath: $PWD/.ssl/root-ca.pem
        containerPath: /opt/ca-certificates/root-ca.pem
        readOnly: true
      - hostPath: $PWD/.ssl/truststore.jks
        containerPath: /opt/ca-certificates/truststore.jks
        readOnly: true
      - hostPath: $PWD/k8s/.local-registry/
        containerPath: "/etc/containerd/certs.d/"
        readOnly: true
  - role: worker
    labels:
      topology.kubernetes.io/zone: "us-central1-a"
      # This is a workaround to be able to use a single k8s node for hostPort mappings needed for north/south traffic into the k8s cluster
      # as only a single worker node can bind to the same hostPort on the host machine (your laptop)... it creates a bottleneck but is acceptable for local development
      ingress-ready: "true"
    image: "kindest/node:v$KUBERNETES_VERSION"
    extraMounts:
      - hostPath: $PWD/.ssl/root-ca.pem
        containerPath: /opt/ca-certificates/root-ca.pem
        readOnly: true
      - hostPath: $PWD/.ssl/truststore.jks
        containerPath: /opt/ca-certificates/truststore.jks
        readOnly: true
      - hostPath: $PWD/k8s/.local-registry/
        containerPath: "/etc/containerd/certs.d/"
        readOnly: true
    extraPortMappings:
    # Port for gateway over http
    - containerPort: 30000
      hostPort: 80
      listenAddress: "127.0.0.1"
      protocol: TCP
    # Port for gateway over https
    - containerPort: 30001
      hostPort: 443
      listenAddress: "127.0.0.1"
      protocol: TCP
    # Port for gateway tcp for postgres
    - containerPort: 30002
      hostPort: 5432
      listenAddress: "127.0.0.1"
      protocol: TCP
  - role: worker
    labels:
      topology.kubernetes.io/zone: "us-central1-b"
      ingress-ready: "false"
    image: "kindest/node:v$KUBERNETES_VERSION"
    extraMounts:
      - hostPath: $PWD/.ssl/root-ca.pem
        containerPath: /opt/ca-certificates/root-ca.pem
        readOnly: true
      - hostPath: $PWD/.ssl/truststore.jks
        containerPath: /opt/ca-certificates/truststore.jks
        readOnly: true
      - hostPath: $PWD/k8s/.local-registry/
        containerPath: "/etc/containerd/certs.d/"
        readOnly: true
  - role: worker
    labels:
      topology.kubernetes.io/zone: "us-central1-c"
      ingress-ready: "false"
    image: "kindest/node:v$KUBERNETES_VERSION"
    extraMounts:
      - hostPath: $PWD/.ssl/root-ca.pem
        containerPath: /opt/ca-certificates/root-ca.pem
        readOnly: true
      - hostPath: $PWD/.ssl/truststore.jks
        containerPath: /opt/ca-certificates/truststore.jks
        readOnly: true
      - hostPath: $PWD/k8s/.local-registry/
        containerPath: "/etc/containerd/certs.d/"
        readOnly: true
